server {
    listen 8080;                  # Port to listen on 
    host 127.0.0.1;               # Interface 
    server_name mysite.com;       # Optional, but good for testing 
    client_max_body_size 10M;     # Limit for uploads 
    error_page 404 /404.html;     # Default error page 

    # Rule for a specific route (URL)
    location / {
        root /var/www/html;       # Where the files live 
        index index.html;         # Default file 
        allow_methods GET POST;   # Accepted methods 
        autoindex on;             # Directory listing 
    }

    # Rule for uploading files 
    location /upload {
        root /var/www/uploads;
        allow_methods POST;
        upload_enable on;         # Custom flag to authorize uploads 
    }
    
    # Rule for CGI scripts 
        root /var/www/cgi;
        allow_methods GET POST;
        cgi_extension .php;       # Trigger CGI based on extension 
        cgi_path /usr/bin/php-cgi; 
    }

